# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e757c158d31a649209fefeec45d9cf714567443f95763c09f06924eb85973457e9ee763d0c0f1fcabbc08cf042ce75a9321969043c75665c2311fd692c6eb6e9

test:
  secret_key_base: fdbcd503df1c5b7d8ed39cec3269780ed17ab66021883d75ece1e1a2cd28cbca15f6f65ed51336c005be46eee0c9d6671383bc311dcef549428c6006c7a99eba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
